baseURL: "https://nmdra.github.io"
languageCode: "en"
title: Nimendra
theme: ["hugo-notice", "PaperMod"]

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Nimendra
  description: "Welcome to My Blog!"
  keywords: [Blog]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  showtoc: true
  disableScrollToTop: false
  assets:
    disableHLJS: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "summary"]

  # Logo and name shown on top left of site
  label:
    text: "Nimendra"

  # profile-mode
  # profileMode:
  #   # Needs to be explicitly set
  #   enabled: true
  #   title: "Hey \U0001F44B, I'm Nimendra"
  #   subtitle: "Self Learner | Cloud and DevOps Enthusiast | Bookworm"
  #   imageUrl: images/profile.webp
  #   imageWidth: 150
  #   imageHeight: 150
  #   imageTitle: "Profile image"
  #   buttons:
  #     - name: About
  #       url: /about/#about-me
  #     - name: Blog
  #       url: /blog
  #     - name: Contact
  #       url: /about/#contact-me
  #     # - name: Resume
  #     #   url: "https://github.com/nmdra/Resume/releases/latest/download/Nimendra-Resume.pdf"
  #     - name: Resume
  #       url: /resume
  #
  #
  homeInfoParams:
    Title: "Hey 👋, I'm Nimendra"
    Content: "I'm a self-learner, passionate about Cloud and DevOps, and an avid bookworm.  
      Explore more **[about me](/about/#about-me)**, check out my **[blog](/blog)**, or **[get in touch](/about/#contact-me)**.  
      You can also view my ***[resume](https://github.com/nmdra/Resume/releases/latest/download/Nimendra-Resume.pdf)***."

  socialIcons:
    - name: github
      url: "https://github.com/nmdra"
    - name: linkedin
      url: "https://www.linkedin.com/in/nimendra/"
    - name: x
      url: "https://x.com/nimendra_"
    - name: bluesky
      url: "https://bsky.app/profile/nimendra.xyz"
    - name: email
      url: "mailto:nimendraonline@gmail.com"
    - name: "rss"
      url: "https://blog.nimendra.xyz/index.xml"

  cover:
    linkFullImages: true
    hidden: false
    hiddenInList: false
    hiddenInSingle: true

outputs:
  home:
    - HTML
    - JSON
    - RSS

menu:
  main:
    - identifier: search
      name: Search
      url: /search
      weight: 6
    - identifier: about
      name: About
      url: /about
      weight: 1
    - identifier: blog
      name: Blog
      url: /blog
      weight: 2
    - identifier: projects
      name: Projects
      url: https://github.com/nmdra
      weight: 3
    - identifier: bookmarks
      name: Bookmarks
      url: https://bookmarks.nimendra.xyz/bookmarks/shared
      weight: 5
    - identifier: uses
      name: Uses
      url: /uses
      weight: 4

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNos: true
    lineNoStart: 0
    noClasses: false
    noHl: false
    tabWidth: 4
    style: tokyonight-storm
  tableOfContents:
    endLevel: 4

