baseURL: "https://nmdra.github.io"
languageCode: "en"
title: Nimendra
theme: PaperMod

minify:
  disableXML: true
  minifyOutput: true

# googleAnalytics: G-C917SZ3ZQE

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Nimendra
  description: "Welcome to my website!"
  keywords: [Blog]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  showtoc: true
  disableScrollToTop: false

  assets:
    disableHLJS: true

  # Logo and name shown on top left of site
  label:
    text: "Nimendra"

  # profile-mode
  profileMode:
    # Needs to be explicitly set
    enabled: true
    title: "Hey \U0001F44B, I'm Nimendra"
    subtitle: "Tech Enthusiast | Software Engineering Undergraduate"
    imageUrl: images/profile.webp
    imageWidth: 150
    imageHeight: 150
    imageTitle: "Profile image"
    buttons:
      - name: Blog
        url: /blog
      - name: About Me
        url: /about/#about-me
      - name: Contact
        url: /about/#contact-me

  socialIcons:
    # - name: cv
    #   url:
    - name: github
      url: "https://github.com/nmdra"
    - name: linkedin
      url: "https://www.linkedin.com/in/nimendra/"
    - name: x
      url: "https://x.com/nimendra_"
    - name: email
      url: "mailto:nimendraonline@gmail.com"

  cover:
    linkFullImages: true
    hidden: false
    hiddenInList: false
    hiddenInSingle: true



outputs:
  home:
    - HTML
    - JSON
    - RSS

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 1
    - identifier: blog
      name: Blog
      url: /blog
      weight: 2
    - identifier: projects
      name: Projects
      url: https://github.com/nmdra
      weight: 5
    - identifier: links
      name: Links
      url: /links
      weight: 4
    - identifier: uses
      name: Uses
      url: /uses
      weight: 3

markup:
  tableOfContents:
    endLevel: 6
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    noClasses: false
    noHl: false
    tabWidth: 4
    style: dracula

